web-absen-master-master/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('');
});*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/about', function(){
	return View::make('about');
});
Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');
Route::post('/logout','Auth\LoginController@logout');

//absensi Route
Route::get('/rekap', 'AbsensiController@Rekap')->name('absensis.rekap');
Route::resource('absensis', 'AbsensiController');
Route::get('/export', 'AbsensiController@export')->name('absensis.export');

Route::group(['middleware' => 'auth'],function(){

	Route::get('/home', 'HomeController@index')->name('home');

	//karyawan Route
	Route::get('/person', 'KaryawanController@Person')->name('karyawans.person');

	Route::get('/download', 'KaryawanController@export_image')->name('karyawans.export_image');


	Route::group(['middleware' => 'akses'],function(){

			Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('register');

			Route::post('/register','Auth\RegisterController@register');

			Route::resource('levels', 'LevelController');

			Route::resource('namePositions', 'NamePositionController');

			Route::resource('units', 'UnitController');

			Route::resource('sektors', 'SektorController');

			Route::resource('statuses', 'StatusController');
			
			Route::resource('agamas', 'AgamaController');	

			Route::resource('users', 'UserController');

			Route::resource('karyawans', 'KaryawanController');
			Route::get('/exportkaryawan', 'App\Http\Controllers\KaryawanController@export')->name('karyawans.export');


			Route::get('/dbkaryawan', 'KaryawanController@export')->name('karyawans.export');
			Route::post('/import', 'KaryawanController@import')->name('karyawans.import');

			Route::post('/usersimport', 'UserController@import')->name('users.import');

			Route::resource('namePositions', 'NamePositionController');
			
			Route::get('/dowdatagaji', 'PenggajianController@export')->name('penggajians.export');
			Route::post('/penggajianImport', 'PenggajianController@import')->name('penggajian.import');

            Route::resource('fotoRecognitions', 'FotoRecognitionController');

            Route::resource('jamKerjas', 'JamKerjaController');
    });

});

web-absen-master-master/app/Models/JamKerja.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class JamKerja
 * @package App\Models
 * @version September 3, 2020, 10:19 am WITA
 *
 * @property string $ket
 * @property string|\Carbon\Carbon $jam_awal
 * @property string|\Carbon\Carbon $jam_akhir
 */
class JamKerja extends Model
{
    use SoftDeletes;

    public $table = 'jamkerja';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected $primaryKey="id";

    protected $dates = ['deleted_at'];



    public $fillable = [
        'ket',
        'jam_awal',
        'jam_akhir'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ket' => 'string',
        'jam_awal' => 'datetime',
        'jam_akhir' => 'datetime'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
//        'ket' => 'nullable|string|max:45',
//        'jam_awal' => 'nullable',
//        'jam_akhir' => 'nullable',
//        'created_at' => 'nullable',
//        'updated_at' => 'nullable',
//        'deleted_at' => 'nullable'
    ];


}

web-absen-master-master/app/Http/Controllers/JamKerjaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateJamKerjaRequest;
use App\Http\Requests\UpdateJamKerjaRequest;
use App\Repositories\JamKerjaRepository;
use App\Http\Controllers\AppBaseController;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Flash;
use Response;

class JamKerjaController extends AppBaseController
{
    /** @var  JamKerjaRepository */
    private $jamKerjaRepository;

    public function __construct(JamKerjaRepository $jamKerjaRepo)
    {
        $this->jamKerjaRepository = $jamKerjaRepo;
    }

    /**
     * Display a listing of the JamKerja.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $jamKerjas = $this->jamKerjaRepository->all();

        return view('jam_kerjas.index')
            ->with('jamKerjas', $jamKerjas);
    }

    /**
     * Show the form for creating a new JamKerja.
     *
     * @return Response
     */
    public function create()
    {
        return view('jam_kerjas.create');
    }

    /**
     * Store a newly created JamKerja in storage.
     *
     * @param CreateJamKerjaRequest $request
     *
     * @return Response
     */
    public function store(CreateJamKerjaRequest $request)
    {
        $input = $request->all();

        $input['jam_awal']=Carbon::createFromFormat('Y-m-d\TH:i', $input['jam_awal'])->toDateTimeString();
        $input['jam_akhir']=Carbon::createFromFormat('Y-m-d\TH:i', $input['jam_akhir'])->toDateTimeString();

        $jamKerja = $this->jamKerjaRepository->create($input);

        Flash::success('Jam Kerja saved successfully.');

        return redirect(route('jamKerjas.index'));
    }

    /**
     * Display the specified JamKerja.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $jamKerja = $this->jamKerjaRepository->find($id);

        if (empty($jamKerja)) {
            Flash::error('Jam Kerja not found');

            return redirect(route('jamKerjas.index'));
        }

        return view('jam_kerjas.show')->with('jamKerja', $jamKerja);
    }

    /**
     * Show the form for editing the specified JamKerja.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $jamKerja = $this->jamKerjaRepository->find($id);

        if (empty($jamKerja)) {
            Flash::error('Jam Kerja not found');

            return redirect(route('jamKerjas.index'));
        }

        return view('jam_kerjas.edit')->with('jamKerja', $jamKerja);
    }

    /**
     * Update the specified JamKerja in storage.
     *
     * @param int $id
     * @param UpdateJamKerjaRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateJamKerjaRequest $request)
    {
        $jamKerja = $this->jamKerjaRepository->find($id);

        $input = $request->all();

        $input['jam_awal']=Carbon::createFromFormat('Y-m-d\TH:i', $input['jam_awal'])->toDateTimeString();
        $input['jam_akhir']=Carbon::createFromFormat('Y-m-d\TH:i', $input['jam_akhir'])->toDateTimeString();

        if (empty($jamKerja)) {
            Flash::error('Jam Kerja not found');

            return redirect(route('jamKerjas.index'));
        }

        $jamKerja = $this->jamKerjaRepository->update($input, $id);

        Flash::success('Jam Kerja updated successfully.');

        return redirect(route('jamKerjas.index'));
    }

    /**
     * Remove the specified JamKerja from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $jamKerja = $this->jamKerjaRepository->find($id);

        if (empty($jamKerja)) {
            Flash::error('Jam Kerja not found');

            return redirect(route('jamKerjas.index'));
        }

        $this->jamKerjaRepository->delete($id);

        Flash::success('Jam Kerja deleted successfully.');

        return redirect(route('jamKerjas.index'));
    }
}

web-absen-master-master/resources/views/jam_kerjas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Jam Kerja
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'jamKerjas.store']) !!}

                        @include('jam_kerjas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

web-absen-master-master/resources/views/jam_kerjas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Jam Kerja
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="card card-body">
                   {!! Form::model($jamKerja, ['route' => ['jamKerjas.update', $jamKerja->id], 'method' => 'patch']) !!}

                        @include('jam_kerjas.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

web-absen-master-master/resources/views/jam_kerjas/fields.blade.php
<!-- Ket Field -->
<div class="form-group col-sm-8">
    {!! Form::label('ket', 'Waktu:') !!}
    {!! Form::text('ket', null, ['class' => 'form-control','maxlength' => 45,'maxlength' => 45]) !!}
</div>

<!-- Jam Awal Field -->
<div class="form-group col-sm-8">
    {!! Form::label('jam_awal', 'Jam Awal:') !!}
{{--    {!! Form::date('jam_awal', null, ['class' => 'form-control','id'=>'jam_awal']) !!}--}}
    <input id="jam_awal" name="jam_awal" class="form-control" type="datetime-local">
</div>

{{--@push('scripts')--}}
{{--    <script type="text/javascript">--}}
{{--        $('#jam_awal').datetimepicker({--}}
{{--            format: 'YYYY-MM-DD HH:mm:ss',--}}
{{--            useCurrent: false--}}
{{--        })--}}
{{--    </script>--}}
{{--@endpush--}}

<!-- Jam Akhir Field -->
<div class="form-group col-sm-8">
    {!! Form::label('jam_akhir', 'Jam Akhir:') !!}
{{--    {!! Form::date('jam_akhir', null, ['class' => 'form-control','id'=>'jam_akhir']) !!}--}}
    <input id="jam_akhir" name="jam_akhir" class="form-control" type="datetime-local">
</div>

{{--@push('scripts')--}}
{{--    <script type="text/javascript">--}}
{{--        $('#jam_akhir').datetimepicker({--}}
{{--            format: 'YYYY-MM-DD HH:mm:ss',--}}
{{--            useCurrent: false--}}
{{--        })--}}
{{--    </script>--}}
{{--@endpush--}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('jamKerjas.index') }}" class="btn btn-default">Cancel</a>
</div>

web-absen-master-master/resources/views/jam_kerjas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Pengaturan Jam Absensi</h1>
        @if($jamKerjas->count() == 2 )

        @else
            <h1 class="pull-right">
                <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('jamKerjas.create') }}">Add New</a>
            </h1>
        @endif
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('jam_kerjas.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

web-absen-master-master/resources/views/jam_kerjas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Jam Kerja
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('jam_kerjas.show_fields')
                    <a href="{{ route('jamKerjas.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

web-absen-master-master/resources/views/jam_kerjas/show_fields.blade.php
<!-- Ket Field -->
<div class="form-group">
    {!! Form::label('ket', 'Ket:') !!}
    <p>{{ $jamKerja->ket }}</p>
</div>

<!-- Jam Awal Field -->
<div class="form-group">
    {!! Form::label('jam_awal', 'Jam Awal:') !!}
    <p>{{ $jamKerja->jam_awal }}</p>
</div>

<!-- Jam Akhir Field -->
<div class="form-group">
    {!! Form::label('jam_akhir', 'Jam Akhir:') !!}
    <p>{{ $jamKerja->jam_akhir }}</p>
</div>

web-absen-master-master/resources/views/jam_kerjas/table.blade.php
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Data Jam Absen</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Jadwal</th>
        <th>Jam Awal</th>
        <th>Jam Akhir</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($jamKerjas as $jamKerja)
            <tr>
                <td>{{ $jamKerja->ket }}</td>
            <td>{{ \Carbon\Carbon::parse($jamKerja->jam_awal)->format('H:i') }} </td>
            <td>{{ \Carbon\Carbon::parse($jamKerja->jam_akhir)->format('H:i') }} </td>
                <td>
                    {!! Form::open(['route' => ['jamKerjas.destroy', $jamKerja->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('jamKerjas.show', [$jamKerja->id]) }}" class='btn btn-default btn-xs'><i class="fas fa-eye"></i></a>
                        <a href="{{ route('jamKerjas.edit', [$jamKerja->id]) }}" class='btn btn-default btn-xs'><i class="fas fa-edit"></i></a>
{{--                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}--}}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
</div>