web-absen-master-master/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('');
});*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/about', function(){
	return View::make('about');
});
Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');
Route::post('/logout','Auth\LoginController@logout');

//absensi Route
Route::get('/rekap', 'AbsensiController@Rekap')->name('absensis.rekap');
Route::resource('absensis', 'AbsensiController');
Route::get('/export', 'AbsensiController@export')->name('absensis.export');

Route::group(['middleware' => 'auth'],function(){

	Route::get('/home', 'HomeController@index')->name('home');

	//karyawan Route
	Route::get('/person', 'KaryawanController@Person')->name('karyawans.person');

	Route::get('/download', 'KaryawanController@export_image')->name('karyawans.export_image');


	Route::group(['middleware' => 'akses'],function(){

			Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('register');

			Route::post('/register','Auth\RegisterController@register');

			Route::resource('levels', 'LevelController');

			Route::resource('namePositions', 'NamePositionController');

			Route::resource('units', 'UnitController');

			Route::resource('sektors', 'SektorController');

			Route::resource('statuses', 'StatusController');
			
			Route::resource('agamas', 'AgamaController');	

			Route::resource('users', 'UserController');

			Route::resource('karyawans', 'KaryawanController');
			Route::get('/exportkaryawan', 'App\Http\Controllers\KaryawanController@export')->name('karyawans.export');


			Route::get('/dbkaryawan', 'KaryawanController@export')->name('karyawans.export');
			Route::post('/import', 'KaryawanController@import')->name('karyawans.import');

			Route::post('/usersimport', 'UserController@import')->name('users.import');

			Route::resource('namePositions', 'NamePositionController');
			
			Route::get('/dowdatagaji', 'PenggajianController@export')->name('penggajians.export');
			Route::post('/penggajianImport', 'PenggajianController@import')->name('penggajian.import');

            Route::resource('fotoRecognitions', 'FotoRecognitionController');

            Route::resource('jamKerjas', 'JamKerjaController');
    });

});

web-absen-master-master/app/Models/NamePosition.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class NamePosition
 * @package App\Models
 * @version February 2, 2020, 9:01 am UTC
 *
 * @property \App\Models\Level levels
 * @property \Illuminate\Database\Eloquent\Collection karyawans
 * @property string nama
 * @property integer levels_id
 */
class NamePosition extends Model
{
    use SoftDeletes;

    public $table = 'name_posisions';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'nama',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nama' => 'string',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function levels()
    {
        return $this->belongsTo(\App\Models\Level::class, 'levels_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function karyawans()
    {
        return $this->hasMany(\App\Models\Karyawan::class, 'name_posisions_id');
    }
}

web-absen-master-master/app/Http/Controllers/NamePositionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateNamePositionRequest;
use App\Http\Requests\UpdateNamePositionRequest;
use App\Repositories\NamePositionRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class NamePositionController extends AppBaseController
{
    /** @var  NamePositionRepository */
    private $namePositionRepository;

    public function __construct(NamePositionRepository $namePositionRepo)
    {
        $this->namePositionRepository = $namePositionRepo;
    }

    /**
     * Display a listing of the NamePosition.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $namePositions = $this->namePositionRepository->all();

        return view('name_positions.index')
            ->with('namePositions', $namePositions);
    }

    /**
     * Show the form for creating a new NamePosition.
     *
     * @return Response
     */
    public function create()
    {

        return view('name_positions.create');
    }

    /**
     * Store a newly created NamePosition in storage.
     *
     * @param CreateNamePositionRequest $request
     *
     * @return Response
     */
    public function store(CreateNamePositionRequest $request)
    {
        $input = $request->all();

        $namePosition = $this->namePositionRepository->create($input);

        Flash::success('Name Position saved successfully.');

        return redirect(route('namePositions.index'));
    }

    /**
     * Display the specified NamePosition.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $namePosition = $this->namePositionRepository->find($id);

        if (empty($namePosition)) {
            Flash::error('Name Position not found');

            return redirect(route('namePositions.index'));
        }

        return view('name_positions.show')->with('namePosition', $namePosition);
    }

    /**
     * Show the form for editing the specified NamePosition.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $namePosition = $this->namePositionRepository->find($id);

        if (empty($namePosition)) {
            Flash::error('Name Position not found');

            return redirect(route('namePositions.index'));
        }

        return view('name_positions.edit',compact('namePosition'));
    }

    /**
     * Update the specified NamePosition in storage.
     *
     * @param int $id
     * @param UpdateNamePositionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateNamePositionRequest $request)
    {
        $namePosition = $this->namePositionRepository->find($id);

        if (empty($namePosition)) {
            Flash::error('Name Position not found');

            return redirect(route('namePositions.index'));
        }

        $namePosition = $this->namePositionRepository->update($request->all(), $id);

        Flash::success('Name Position updated successfully.');

        return redirect(route('namePositions.index'));
    }

    /**
     * Remove the specified NamePosition from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $namePosition = $this->namePositionRepository->find($id);

        if (empty($namePosition)) {
            Flash::error('Name Position not found');

            return redirect(route('namePositions.index'));
        }

        $this->namePositionRepository->delete($id);

        Flash::success('Name Position deleted successfully.');

        return redirect(route('namePositions.index'));
    }
}

web-absen-master-master/resources/views/name_positions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Name Position
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="card-body">
                <div class="row">
                    {!! Form::open(['route' => 'namePositions.store']) !!}

                        @include('name_positions.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

web-absen-master-master/resources/views/name_positions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Name Position
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="card-body">
               <div class="row">
                   {!! Form::model($namePosition, ['route' => ['namePositions.update', $namePosition->id], 'method' => 'patch']) !!}

                        @include('name_positions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

web-absen-master-master/resources/views/name_positions/fields.blade.php
<!-- Nama Field -->
<div class="form-group col-sm-12">
    {!! Form::label('nama', 'Nama:') !!}
    {!! Form::text('nama', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('namePositions.index') }}" class="btn btn-default">Cancel</a>
</div>

web-absen-master-master/resources/views/name_positions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Jabatan/Name Position</h1><br>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('namePositions.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('name_positions.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

web-absen-master-master/resources/views/name_positions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Name Position
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('name_positions.show_fields')
                    <a href="{{ route('namePositions.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

web-absen-master-master/resources/views/name_positions/show_fields.blade.php
<!-- Nama Field -->
<div class="form-group">
    {!! Form::label('nama', 'Nama:') !!}
    <p>{{ $namePosition->nama }}</p>
</div>

<!-- Levels Id Field -->
<div class="form-group">
    {!! Form::label('levels_id', 'Levels Id:') !!}
    <p>{{ $namePosition->levels_id }}</p>
</div>

web-absen-master-master/resources/views/name_positions/table.blade.php
<div class="table-responsive">
    <table class="table" id="namePositions-table">
        <thead>
            <tr>
                <th>Nama</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($namePositions as $namePosition)
            <tr>
                <td>{{ $namePosition->nama }}</td>
                <td>
                    {!! Form::open(['route' => ['namePositions.destroy', $namePosition->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('namePositions.show', [$namePosition->id]) }}" class='btn btn-default btn-xs'><i class="fas fa-eye"></i></a>
                        <a href="{{ route('namePositions.edit', [$namePosition->id]) }}" class='btn btn-default btn-xs'><i class="fas fa-edit"></i></a>
                        {!! Form::button('<i class="fas fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>