web-absen-master-master/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('');
});*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/about', function(){
	return View::make('about');
});
Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');
Route::post('/logout','Auth\LoginController@logout');

//absensi Route
Route::get('/rekap', 'AbsensiController@Rekap')->name('absensis.rekap');
Route::resource('absensis', 'AbsensiController');
Route::get('/export', 'AbsensiController@export')->name('absensis.export');

Route::group(['middleware' => 'auth'],function(){

	Route::get('/home', 'HomeController@index')->name('home');

	//karyawan Route
	Route::get('/person', 'KaryawanController@Person')->name('karyawans.person');

	Route::get('/download', 'KaryawanController@export_image')->name('karyawans.export_image');


	Route::group(['middleware' => 'akses'],function(){

			Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('register');

			Route::post('/register','Auth\RegisterController@register');

			Route::resource('levels', 'LevelController');

			Route::resource('namePositions', 'NamePositionController');

			Route::resource('units', 'UnitController');

			Route::resource('sektors', 'SektorController');

			Route::resource('statuses', 'StatusController');
			
			Route::resource('agamas', 'AgamaController');	

			Route::resource('users', 'UserController');

			Route::resource('karyawans', 'KaryawanController');
			Route::get('/exportkaryawan', 'App\Http\Controllers\KaryawanController@export')->name('karyawans.export');


			Route::get('/dbkaryawan', 'KaryawanController@export')->name('karyawans.export');
			Route::post('/import', 'KaryawanController@import')->name('karyawans.import');

			Route::post('/usersimport', 'UserController@import')->name('users.import');

			Route::resource('namePositions', 'NamePositionController');
			
			Route::get('/dowdatagaji', 'PenggajianController@export')->name('penggajians.export');
			Route::post('/penggajianImport', 'PenggajianController@import')->name('penggajian.import');

            Route::resource('fotoRecognitions', 'FotoRecognitionController');

            Route::resource('jamKerjas', 'JamKerjaController');
    });

});

web-absen-master-master/resources/views/rekap_absen/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Absensi
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'absensis.store']) !!}

                        @include('absensis.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

web-absen-master-master/resources/views/rekap_absen/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Absensi
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($absensi, ['route' => ['absensis.update', $absensi->id], 'method' => 'patch']) !!}

                        @include('absensis.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

web-absen-master-master/resources/views/rekap_absen/fields.blade.php
<!-- Time In Field -->
<div class="form-group col-sm-6">
    {!! Form::label('time_in', 'Time In:') !!}
    {!! Form::date('time_in', null, ['class' => 'form-control','id'=>'time_in']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#time_in').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endsection

<!-- Time Out Field -->
<div class="form-group col-sm-6">
    {!! Form::label('time_out', 'Time Out:') !!}
    {!! Form::date('time_out', null, ['class' => 'form-control','id'=>'time_out']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#time_out').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endsection

<!-- Latitude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('latitude', 'Latitude:') !!}
    {!! Form::number('latitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Longtitude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('longtitude', 'Longtitude:') !!}
    {!! Form::number('longtitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Karyawans Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('karyawans_id', 'Karyawans Id:') !!}
    {!! Form::number('karyawans_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('absensis.index') }}" class="btn btn-default">Cancel</a>
</div>

web-absen-master-master/resources/views/rekap_absen/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Absensis</h1>
        <form action="{{ route('absensis.rekap') }}" method="get">
            <div class="input-group mb-3 col-md-4 float-right">
                {!! Form::date('start', null, ['class' => 'form-control','id'=>'start']) !!}
                @section('scripts')
                    <script type="text/javascript">
                        $('#start').datetimepicker({
                            format: 'YYYY-MM-DD',
                            useCurrent: false
                        })
                    </script>
                @endsection
                To
                {!! Form::date('end', null, ['class' => 'form-control','id'=>'end']) !!}
                @section('scripts')
                    <script type="text/javascript">
                        $('#end').datetimepicker({
                            format: 'YYYY-MM-DD',
                            useCurrent: false
                        })
                    </script>
                @endsection
                <div class="input-group-append">
                    <button class="btn btn-secondary" type="submit">Cari</button>
                </div>            
            </div>
        </form>
        
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('rekap_absen.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>

@endsection

web-absen-master-master/resources/views/rekap_absen/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Absensi
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('absensis.show_fields')
                    <a href="{{ route('absensis.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

web-absen-master-master/resources/views/rekap_absen/show_fields.blade.php
<!-- Time In Field -->
<div class="form-group">
    {!! Form::label('time_in', 'Time In:') !!}
    <p>{{ $absensi->time_in }}</p>
</div>

<!-- Time Out Field -->
<div class="form-group">
    {!! Form::label('time_out', 'Time Out:') !!}
    <p>{{ $absensi->time_out }}</p>
</div>

<!-- Latitude Field -->
<div class="form-group">
    {!! Form::label('latitude', 'Latitude:') !!}
    <p>{{ $absensi->latitude }}</p>
</div>

<!-- Longtitude Field -->
<div class="form-group">
    {!! Form::label('longtitude', 'Longtitude:') !!}
    <p>{{ $absensi->longtitude }}</p>
</div>

<!-- Karyawans Id Field -->
<div class="form-group">
    {!! Form::label('karyawans_id', 'Karyawans Id:') !!}
    <p>{{ $absensi->karyawans_id }}</p>
</div>

web-absen-master-master/resources/views/rekap_absen/table.blade.php
<div class="table-responsive">
    <table class="table" id="absensis-table">
        <thead>
            <tr>
                <th>Nama Karyawan</th>
                <th>Time In</th>
                <th>Time Out</th>
                <th>Latitude</th>
                <th>Longtitude</th>
                
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($absensis as $absensi)
            <tr>
                <td>{{ $absensi->karyawans->nama_lengkap }}</td>
                <td>{{ $absensi->time_in }}</td>
                <td>{{ $absensi->time_out }}</td>
                <td>{{ $absensi->latitude }}</td>
                <td>{{ $absensi->longtitude }}</td>
                
                <td>
                    {!! Form::open(['route' => ['absensis.destroy', $absensi->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('absensis.show', [$absensi->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('absensis.edit', [$absensi->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>